sudo: required
dist: trusty
language: c
compiler: gcc
before_install:
  - echo 'deb http://archive.ubuntu.com/ubuntu/ wily universe' | sudo tee /etc/apt/sources.list.d/wily.list
  - echo 'deb http://apt.cadrian.net/ unstable main' | sudo tee /etc/apt/sources.list.d/cadrian.list
  - "sudo apt-get update -q"
  - "sudo apt-get install -q libzmq3-dev libuv1-dev libgcrypt20-dev libsqlite3-dev libcad-dev yacjp-dev"
script:
  - "make clean test; sudo dpkg -i packaging/target/circus-*.deb"
cache:
  apt: true
