sudo: required
dist: trusty
language: c
compiler: gcc
before_install:
  - echo 'deb http://archive.ubuntu.com/ubuntu/ yakkety main universe' | sudo tee /etc/apt/sources.list.d/xenial.list
  - echo 'deb http://apt.cadrian.net/ unstable main' | sudo tee /etc/apt/sources.list.d/cadrian.list
  - "sudo apt-get -q update"
  - "sudo apt-get -q -y --allow-unauthenticated install gcc libc6 libc6-dev libzmq3-dev libuv1-dev libgcrypt20-dev libsqlite3-dev libcad-dev libyacjp-dev libffcall1-dev"
script:
  - "make clean test"
after_success:
  - "sudo dpkg -i packaging/target/circus-*.deb"
cache:
  apt: true
